# Soluciones - Objetos Globales y Utilidades

## Reto 9.1 {#sec-sol-cap9-reto1}

La respuesta del [Reto 9.1](#sec-cap9-reto1) es:

**A: `'{"level":80, "health":25}'`**

**Explicación:**

[JSON.stringify](#glos-json_stringify) puede recibir un segundo parámetro opcional denominado `replacer`, puede ser una función o un arreglo, y se encarga de hacer un filtro de las propiedades del objeto que deseamos convertir a `string`, en el ejemplo solo deseamos convertir las propiedades `["level", "health"]`, ignorando `username`. 


---

## Reto 9.2 {#sec-sol-cap9-reto2}

La respuesta del [Reto 9.2](#sec-cap9-reto2) es:

**B. `9`, `10`, `10`**

**Explicación:**

JavaScript tiene 3 métodos pertenecientes al objeto `Math` útiles para redondeo de números.

* [Math.floor](#glos-math_floor) Siempre redondea el valor hacia abajo.

* [Math.ceil](#glos-math_ceil) Siempre redondea el valor hacia arriba.

* [Math.round](#glos-math_round) Redondea el valor de una manera un poco más inteligente, siguiendo las reglas de redondeo que nos enseñaron en colegio.

Los 3 métodos tienen inferencia de tipos, esto quiere decir que si no le pasamos un valor numérico como parámetro, JavaScript intentará hacer su mejor esfuerzo para poder realizar la operación.


---

## Reto 9.3 {#sec-sol-cap9-reto3}

La respuesta del [Reto 9.3](#sec-cap9-reto3) es:

**D: `"Oh no an error! Hello world!"`**

**Explicación:**

La función `greeting` con la palabra reservada `throw` genera una excepción de tipo `string` en el código.

La función `sayHi` consta de una sentencia `try...catch`, recordemos que si no hay ningún tipo de excepción el código ejecuta el bloque `try` pero como si generamos una excepción entonces entramos al bloque `catch` donde el parámetro `e` adopta el valor de la excepción, o sea, `Hello world!`. Por eso el resultado es `"Oh no an error! Hello world!"`